### ISSUE TITLE
Random Quote Generator

### ISSUE THREAD

**Issue by nperez0111** [NSuri1/FreeCodeCamp#2]
Your margins/paddings are off on the text box they are not accounting for the name of the author
https://goo.gl/photos/JNqwDLGHtFZ94rDE8 In case the image below doesn't work
![image](https://lh3.googleusercontent.com/yecab3bmxrgRNHfdfhhIm-MYnl3IDoFTd1xqtu_0KkkmjrK3hSh7K-wlLngU2-pb-PsvIO1BKv7DsPlRscOQiGGHgx5sBfSyQp3QrOv8CP-fuur1Dl0d6WCdZdqGroa1METziPckssg2Z9Oq696j34VtqC9v6IkTXzc7OpsYI005i4SC1Y8C9XfyTKcbjMx41MsWKWrQeUVd2vJK-Bk3BCbUw4ajG7Nc8cGUDelQNXnOl_O5ywW6fhx_7eQR0RdQ_YZs81lBDqmwxX1w4MaQGoJmff5yA-c8H__F8OKH3-KDh4cLUoaNY-niO1n72zm-aV972qzvhJFQbT70eXqvqhAQTs_1qNpVK5tdR_OC250cE4MNBv9Mg17nOxPg0mmreJTgdoRqZ1_wDpHOoGZI1l3g4Q8XhEgNWynZF8xXNL711w6HbDzVvOAe-ERZ-cXEz0XVV7HytQhhcSiNdA2lHeS8CG2-wChu0Lk4MnGSKbRa-UZVi-6eEs8MwQ8vklow7O-a2JIcwlZ1XrBzvuZgt3lB0lCne7P8-73FVw3b3JeATgXFG6LH9ckwo6gHL3I2GeaDplxRIiZKjBk--Nj9PiSjYUPgbQ5FHy5_RmoQkx9tHrqfvGCgTQ=w604-h190-no)

**Comment by NSuri1** [comment]
Thanks for pointing that out! I removed the absolute positioning
